ietf-tools/author-tools

- .github/workflows/python-app.yml
- Dockerfile
- at/utils/processor.py
- constraints.txt
- requirements.txt
- tests/data/draft-smoke-signals-00.xml
- tests/test_utils_processor.py
Due to the complexity of how xml2rfc options are set,
ietf-at is moving to using xml2rfc as a command rather than library for
v2v3, pdf, text, html conversions.
This change also removed the preptool step since it's unnecessary when
moved to xml2rfc command based conversions.
Fixes #11
> Uses default xml2rfc options on conversions

- .github/workflows/docker-publish.yml
GitHub workflow will build and publish a docker image to GitHub packages.
Publishing a new release invokes this GitHub workflow.
> Add docker publish GitHub workflow.

- Dockerfile
> fix: Allow github.com domain for iddiff

- Gemfile.lock
- package-lock.json
- package.json
* [Bump up aasvg to 0.3.1](https://github.com/ietf-tools/ietf-at/commit/1c887ee7ca856dc7a38f095ac7b0828027228549)
* [Bump up kramdown-rfc to 1.6.7](https://github.com/ietf-tools/ietf-at/commit/171b4eaff8a38ac887ffd19ed3cd520d548792ac)
> chore(deps): Update aasvg and kramdown-rfc

- Gemfile.lock
> fix: Add x86_64-linux to Gemfile.lock

- CONTRIBUTING.md
- Dockerfile
- README.md
- api.yml
- at/utils/authentication.py
- tests/test_api_iddiff.py
- tests/test_api_render.py
- tests/test_api_validate.py
- tests/test_api_version.py
- tests/test_utils_authentication.py
Datatracker authentication can be enabled or disabled by changing the
configuration option `REQUIRE_AUTH` to `True` or `False`.
Fixes #103
> feat: Disable requirement for datatracker authentication

- Dockerfile
> fix: Set kramdown-rfc XML host to bib.ietf.org

- Dockerfile
`wget` is required by `idnits`.
Fixes #147
> fix: Install wget as a required dependency in Dockerfile

- api.yml
- at/api.py
- tests/test_api_iddiff.py
When `latest` property is set use the latest document in the series from datataracker for comparison.
Fixes #251
> feat: Introduce new property lastet to /api/iddiff

- at/utils/file.py
- tests/test_api_iddiff.py
- tests/test_utils_file.py
This fix handles cases where the filename can not be determined in downloaded files for iddiff.
Fixes #267
> fix: Handle cases where filename can not be determined

- Dockerfile
- tests/test_api_abnf_extract.py
- tests/test_api_iddiff.py
- tests/test_utils_net.py
Change the URL to https://datatracker.ietf.org/api/rfcdiff-latest-json/
> chore: Update latest draft API URL for datatracker

- at/utils/iddiff.py
- tests/test_api_iddiff.py
- tests/test_utils_iddiff.py
This change introduces 20 seconds timeout for rfcdiff and iddiff operations.
if iddiff operation takes more than 20 seconds, author tools will try to use rfcdiff.
if rfcdiff operation takes more than 20 seconds, a timeout error will be returned.
> fix: iddiff timeout

- api.yml
- at/api.py
- at/utils/text.py
- tests/data/draft-smoke-signals-01.xml
- tests/test_api_iddiff.py
- tests/test_utils_text.py
This change introduces a new parameter `raw`.
When this parameter is set files will not be converted to text.
Fixes #281
> feat: Allow comparing files as it is

- api.yml
- at/api.py
- at/utils/file.py
- at/utils/processor.py
- tests/data/draft-smoke-signals-02.xml
- tests/test_api_clean_svg_ids.py
- tests/test_utils_processor.py
New API call `/api/clean_svg_ids` to fix duplicate SVG `id` attributes in XML.
Fixes #327
> feat: Expose kramdown-rfc-clean-svg-ids

- Dockerfile
The added domains serve the GitHub pages equivalents of GitLab and Codeberg. As adjustments[1] to the i-d-template come in that facilitate more diverse hosting, users will want to diff draft versions from there.
[1]: https://github.com/martinthomson/i-d-template/issues/398
> chore: Allow more GitHub-pages style domains

- at/api.py
- tests/data/draft-iab-xml2rfc-02.txt
- tests/test_api_iddiff.py
Compare with the latest document available in Datatracker when the provided filename doesn't have a version.
Fixes #338
Fixes #347
> fix: Compare with latest when filename doesn't have a version

- Dockerfile
The entry added in https://github.com/ietf-tools/ietf-at/pull/344 was incorrectly using the plural TLD, when the actual TLD is singular ".page".
Sorry for the churn. Pinging @kesara, who should have all the context from yesterday's issue.
> fix: Use correct domain in ALLOWED_DOMAINS

- api.yml
- at/utils/logs.py
- at/utils/validation.py
- tests/data/draft-smoke-signals-00.xml
- tests/test_api_validate.py
- tests/test_utils_logs.py
- tests/test_utils_validation.py
This change adds output from `xml2rfc --warn-bare-unicode` and kramdown-rfc's `echars` to `/api/validate` API call.
Fixes #364
> feat: Add non-ascii character report

- .github/workflows/python-app.yml
- Dockerfile
- api.yml
- at/api.py
- at/utils/version.py
- package-lock.json
- package.json
- tests/test_api_version.py
- tests/test_utils_version.py
This change adds `utftex` and `tex2svg`.
Fixes #352
> feat: Add support for math notation in kramdown-rfc

- README.md
- docker-compose.yml
* `docker-compose` command is renamed as `docker compose`.
* `version` in `docker-compose.yml` file is obsolete now.
> chore: Update docker instructions

- static/abnf.html
- static/about.html
- static/clean-svg-ids.html
- static/doc/index.html
- static/iddiff.html
- static/idnits.html
- static/idnits3.html
- static/index.html
- static/rfcdiff.html
- static/styles/custom.css
- static/svgcheck.html
Fixes #542
This produces a footer similar to that of datatracker.
> feat: Update footer
