.github/workflows/python-app.yml

Automate tests with GitHub Workflow

Adds github workflow

---

.github/workflows/python-app.yml
CONTRIBUTING.md
Dockerfile
constraints.txt
requirements.txt
tests/data/draft-smoke-signals-00.md

* Adds support to kramdown-rfc2629 goat ascii art ( #1 )
* Configures github workflow to run on all branches on push events

Feature/kramdown experimental features - GoAT ASCII Art

---

Dockerfile

Installs Noto fonts on docker instance.
Fix for #8.

Installs Noto fonts on docker instance

---

Dockerfile

Installs roboto mono fonts on docker instance

---

.github/workflows/python-app.yml
Dockerfile
README.md
api.yml
at/api.py
at/utils/processor.py
at/utils/version.py
tests/data/draft-smoke-signals-00.mmark.md
tests/test_api_render.py
tests/test_api_version.py
tests/test_utils_processor.py
tests/test_utils_version.py

Adds support for mmark markdown format

---

api.yml
at/utils/authentication.py
tests/test_api_version.py
tests/test_utils_authentication.py

Updates API not to accpet apikey as a query string

---

api.yml
at/api.py
tests/test_api_version.py
tests/test_utils_authentication.py

Removes apikey requirement from /api/version

---

api.yml
at/utils/authentication.py
tests/test_utils_authentication.py

Adds ability to accept apikey in request headers

---

api.yml
at/utils/authentication.py
tests/test_utils_authentication.py

Changes API key header name to X-API-KEY

---

api.yml
at/api.py

Adds missing error responses to OpenAPI specification

---

at/api.py
at/utils/file.py
at/utils/iddiff.py
constraints.txt
requirements.txt
tests/test_api_iddiff.py
tests/test_utils_file.py
tests/test_utils_iddiff.py

* Identifies the latest draft from datatracker.
* Adds the ability to submit draft names.
* Downloads drafts based on datatracker data.

Adds draft discovery to iddiff

---

.github/workflows/python-app.yml
Dockerfile
Gemfile.lock
api.yml
at/api.py

* Updates kramdown-rfc2629 to 1.5.16
* Strips white spaces from input text
* Adds `/api/iddiff` specifications to API specification
* Sets release 0.3.0

Feature/release 0.3.0

---

Dockerfile
api.yml
package-lock.json
package.json

* Update aasvg to 0.1.7
* Changes for release 0.3.1

Feature/release 0.3.1

---

Dockerfile
api.yml
package-lock.json
package.json

* Remove duplicate allowed domain from docker configuration.
* Change version to 0.3.2.

Feature/release v0.3.2

---

Dockerfile
Gemfile.lock
api.yml
package-lock.json
package.json

* Bump kramdown-rfc2629 to 1.5.26
* Update ietf-at version to 0.3.3

Feature/release 0.3.3

---

at/utils/processor.py

fix: Handle xml2rfc.parser.XmlRfcError exceptions

---

.github/workflows/python-app.yml
CONTRIBUTING.md
Dockerfile
api.yml
at/api.py
at/utils/version.py
requirements.dev.txt
tests/data/draft-smoke-signals-00.md
tests/test_api_version.py
tests/test_utils_version.py

The latest changes to blampe/goat have introduced breaking changes.
Removing this dependency for now.

fix: Remove GoAT dependency

---

at/api.py
tests/test_api_iddiff.py

fix: Ability to use iddiff with just series name

---

CONTRIBUTING.md
Dockerfile
api.yml
at/api.py
tests/data/draft-smoke-signals-00.xml
tests/test_api_iddiff.py
tests/test_api_idnits.py

New endpoint /api/idnits provides plain text idnits output.
Fixes #120

feat: Add idnits endpoint

---

api.yml
at/api.py
at/utils/validation.py
tests/data/draft-smoke-signals-00.xml
tests/test_api_idnits.py
tests/test_utils_validation.py

feat: Add idnits switches

---

api.yml
at/api.py
at/utils/validation.py
tests/test_api_idnits.py
tests/test_utils_validation.py

fix: Set idnits verbose level to 0 by default

---

.github/workflows/python-app.yml
Dockerfile
api.yml
at/api.py
at/utils/abnf.py
tests/data/rfc8855.txt
tests/test_api_abnf_extract.py
tests/test_api_iddiff.py
tests/test_api_version.py
tests/test_utils_abnf.py

Extract ABNF syntax using BAP aex

feat: Add ability to extract ABNF from documents

---

api.yml
at/api.py
at/utils/abnf.py
at/utils/file.py
tests/data/name-error.abnf
tests/data/name.abnf
tests/test_api_abnf_parse.py
tests/test_utils_abnf.py
tests/test_utils_file.py

feat: Add ability to parse ABNF

---

api.yml

docs: Fix typo in iddiff API doc

---

api.yml
at/api.py
tests/test_api_iddiff.py

feat: Use rfcdiff by default for document comparison

---

Dockerfile

Install required fonts from xml2rfc-fonts
Fixes #374

build: Use xml2rfc-fonts

---

.github/workflows/publish.yml
Dockerfile
api.yml
helm/.helmignore
helm/Chart.yaml
helm/templates/NOTES.txt
helm/templates/_helpers.tpl
helm/templates/deployment.yaml
helm/templates/hpa.yaml
helm/templates/ingress.yaml
helm/templates/service.yaml
helm/templates/serviceaccount.yaml
helm/templates/tests/test-connection.yaml
helm/values.yaml

build: Add helm chart

---

README.md
helm/values.yaml
package-lock.json
package.json
static/abnf.html
static/about.html
static/clean-svg-ids.html
static/doc/index.html
static/iddiff.html
static/idnits.html
static/idnits3.html
static/index.html
static/rfcdiff.html
static/svgcheck.html

feat: Rename ietf-at as Author Tools

---

static/about.html

Remove API from the Author Tools label.

chore: Update about.html

---

Dockerfile

Install required fonts from xml2rfc-fonts
Fixes #374

build: Use xml2rfc-fonts (#375)

---

static/index.html

fix: Update card about iddiff

---

Dockerfile

See https://github.com/cabo/kramdown-rfc/issues/235

build: Install required build dependencies for kramdown-rfc

---

.github/workflows/python-app.yml

ci: Run tests when dependencies are updated

---

.github/workflows/python-app.yml
Dockerfile

Ideally this should be rebase after #519 is merged.

chore(deps): Bump up mmark to v2.2.45

---

static/abnf.html
static/about.html
static/clean-svg-ids.html
static/doc/index.html
static/iddiff.html
static/idnits.html
static/idnits3.html
static/index.html
static/rfcdiff.html
static/svgcheck.html

* fix: Add email link to footer. Fixes #526
* fix: Add a footer link to system status. Fixes #508

fix: Update footer

---

constraints.txt
requirements.txt

This also updates other Python dependencies.

chore(deps): Bump up xml2rfc to 3.23.2

---

static/iddiff.html
static/scripts/iddiff.js

feat: Add a switch to select document comparison tool

---

static/idnits.html

fix: Add a link to idnits3

---

static/idnits.html

feat: Update idnits text

---

static/svgcheck.html

feat: Update svgcheck text

---

.github/workflows/python-app.yml
Dockerfile
static/about.html

Also updates LICENSE link for `rfcdiff`.

chore(deps): Bump up rfcdiff to 1.49

---

docker/nginx-default-site.conf

build: Fix issues with trailing forward slash

---

static/scripts/idnits.js

fix: Fix idnits always submission check issue

---

constraints.txt
requirements.txt

Also updates other Python dependencies.

chore(deps): Bump up xml2rfc to 3.26.0

---

Dockerfile

build: Add cache directory

---

static/scripts/abnf.js

fix: Handle ABNF API errors

---

.github/workflows/python-app.yml
Dockerfile
api.yml
at/api.py
at/utils/file.py
at/utils/processor.py
at/utils/text.py
at/utils/validation.py
docker/version.py
static/about.html
static/iddiff.html
static/idnits.html
static/idnits3.html
static/index.html
static/rfcdiff.html
static/scripts/about.js
tests/data/draft-doe-smoke-signals-00.rst
tests/test_api_render.py
tests/test_api_validate.py
tests/test_api_version.py
tests/test_utils_processor.py
tests/test_utils_version.py

feat: Add support for rst2rfcxml
